---
# tasks file for registry
- name: validated if docker registry image already available. 
  shell: "docker images registry | grep -v grep |grep registry | grep '2' | awk '{print $1}'"
  register: check_result
- debug: msg="{{ check_result.stdout }}"
- name: master image exists
  command: echo "Image exits..." 
  when: check_result.stdout == "registry"

- name: master image does exit
  command: echo "Image does not exit..." 
  when: check_result.stdout == ""
- name: copy image, 
  copy: src=files/registry-2.tar.gz dest=/tmp/registry-2.tar.gz 
  when: check_result.stdout == ""
- name: import docke registry image
  shell: docker load < /opt/cluster/registry/templates/registry-2.tar.gz
  when: check_result.stdout == ""
  register: registery_load_result

- name: verify registry is not runing 
  shell: "docker -a | grep regist | grep -v grep | grep registry  | awk '{print $2 }'"
  register: check_container_running



- name: Create registry container.
  shell: docker run -it -p 5000:5000 -d registry:2 
  when: check_container_running.stdout == ""

#- name: import docker image to local host.
#  command: 'docker load < files/registry-2.tar.gz'
